//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SegipFrontend.ServicioSegip {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Persona", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Persona : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ciField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string primer_apellidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string segundo_apellidoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string ci {
            get {
                return this.ciField;
            }
            set {
                if ((object.ReferenceEquals(this.ciField, value) != true)) {
                    this.ciField = value;
                    this.RaisePropertyChanged("ci");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string nombres {
            get {
                return this.nombresField;
            }
            set {
                if ((object.ReferenceEquals(this.nombresField, value) != true)) {
                    this.nombresField = value;
                    this.RaisePropertyChanged("nombres");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string primer_apellido {
            get {
                return this.primer_apellidoField;
            }
            set {
                if ((object.ReferenceEquals(this.primer_apellidoField, value) != true)) {
                    this.primer_apellidoField = value;
                    this.RaisePropertyChanged("primer_apellido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string segundo_apellido {
            get {
                return this.segundo_apellidoField;
            }
            set {
                if ((object.ReferenceEquals(this.segundo_apellidoField, value) != true)) {
                    this.segundo_apellidoField = value;
                    this.RaisePropertyChanged("segundo_apellido");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioSegip.SegipSoap")]
    public interface SegipSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento NumeroDocumento del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BuscarPersonaCI", ReplyAction="*")]
        SegipFrontend.ServicioSegip.BuscarPersonaCIResponse BuscarPersonaCI(SegipFrontend.ServicioSegip.BuscarPersonaCIRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BuscarPersonaCI", ReplyAction="*")]
        System.Threading.Tasks.Task<SegipFrontend.ServicioSegip.BuscarPersonaCIResponse> BuscarPersonaCIAsync(SegipFrontend.ServicioSegip.BuscarPersonaCIRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento PrimerApellido del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BuscarPersonas", ReplyAction="*")]
        SegipFrontend.ServicioSegip.BuscarPersonasResponse BuscarPersonas(SegipFrontend.ServicioSegip.BuscarPersonasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BuscarPersonas", ReplyAction="*")]
        System.Threading.Tasks.Task<SegipFrontend.ServicioSegip.BuscarPersonasResponse> BuscarPersonasAsync(SegipFrontend.ServicioSegip.BuscarPersonasRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BuscarPersonaCIRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BuscarPersonaCI", Namespace="http://tempuri.org/", Order=0)]
        public SegipFrontend.ServicioSegip.BuscarPersonaCIRequestBody Body;
        
        public BuscarPersonaCIRequest() {
        }
        
        public BuscarPersonaCIRequest(SegipFrontend.ServicioSegip.BuscarPersonaCIRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class BuscarPersonaCIRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string NumeroDocumento;
        
        public BuscarPersonaCIRequestBody() {
        }
        
        public BuscarPersonaCIRequestBody(string NumeroDocumento) {
            this.NumeroDocumento = NumeroDocumento;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BuscarPersonaCIResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BuscarPersonaCIResponse", Namespace="http://tempuri.org/", Order=0)]
        public SegipFrontend.ServicioSegip.BuscarPersonaCIResponseBody Body;
        
        public BuscarPersonaCIResponse() {
        }
        
        public BuscarPersonaCIResponse(SegipFrontend.ServicioSegip.BuscarPersonaCIResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class BuscarPersonaCIResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SegipFrontend.ServicioSegip.Persona BuscarPersonaCIResult;
        
        public BuscarPersonaCIResponseBody() {
        }
        
        public BuscarPersonaCIResponseBody(SegipFrontend.ServicioSegip.Persona BuscarPersonaCIResult) {
            this.BuscarPersonaCIResult = BuscarPersonaCIResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BuscarPersonasRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BuscarPersonas", Namespace="http://tempuri.org/", Order=0)]
        public SegipFrontend.ServicioSegip.BuscarPersonasRequestBody Body;
        
        public BuscarPersonasRequest() {
        }
        
        public BuscarPersonasRequest(SegipFrontend.ServicioSegip.BuscarPersonasRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class BuscarPersonasRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string PrimerApellido;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string SegundoApellido;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Nombres;
        
        public BuscarPersonasRequestBody() {
        }
        
        public BuscarPersonasRequestBody(string PrimerApellido, string SegundoApellido, string Nombres) {
            this.PrimerApellido = PrimerApellido;
            this.SegundoApellido = SegundoApellido;
            this.Nombres = Nombres;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BuscarPersonasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BuscarPersonasResponse", Namespace="http://tempuri.org/", Order=0)]
        public SegipFrontend.ServicioSegip.BuscarPersonasResponseBody Body;
        
        public BuscarPersonasResponse() {
        }
        
        public BuscarPersonasResponse(SegipFrontend.ServicioSegip.BuscarPersonasResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class BuscarPersonasResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SegipFrontend.ServicioSegip.Persona[] BuscarPersonasResult;
        
        public BuscarPersonasResponseBody() {
        }
        
        public BuscarPersonasResponseBody(SegipFrontend.ServicioSegip.Persona[] BuscarPersonasResult) {
            this.BuscarPersonasResult = BuscarPersonasResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SegipSoapChannel : SegipFrontend.ServicioSegip.SegipSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SegipSoapClient : System.ServiceModel.ClientBase<SegipFrontend.ServicioSegip.SegipSoap>, SegipFrontend.ServicioSegip.SegipSoap {
        
        public SegipSoapClient() {
        }
        
        public SegipSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SegipSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SegipSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SegipSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SegipFrontend.ServicioSegip.BuscarPersonaCIResponse SegipFrontend.ServicioSegip.SegipSoap.BuscarPersonaCI(SegipFrontend.ServicioSegip.BuscarPersonaCIRequest request) {
            return base.Channel.BuscarPersonaCI(request);
        }
        
        public SegipFrontend.ServicioSegip.Persona BuscarPersonaCI(string NumeroDocumento) {
            SegipFrontend.ServicioSegip.BuscarPersonaCIRequest inValue = new SegipFrontend.ServicioSegip.BuscarPersonaCIRequest();
            inValue.Body = new SegipFrontend.ServicioSegip.BuscarPersonaCIRequestBody();
            inValue.Body.NumeroDocumento = NumeroDocumento;
            SegipFrontend.ServicioSegip.BuscarPersonaCIResponse retVal = ((SegipFrontend.ServicioSegip.SegipSoap)(this)).BuscarPersonaCI(inValue);
            return retVal.Body.BuscarPersonaCIResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SegipFrontend.ServicioSegip.BuscarPersonaCIResponse> SegipFrontend.ServicioSegip.SegipSoap.BuscarPersonaCIAsync(SegipFrontend.ServicioSegip.BuscarPersonaCIRequest request) {
            return base.Channel.BuscarPersonaCIAsync(request);
        }
        
        public System.Threading.Tasks.Task<SegipFrontend.ServicioSegip.BuscarPersonaCIResponse> BuscarPersonaCIAsync(string NumeroDocumento) {
            SegipFrontend.ServicioSegip.BuscarPersonaCIRequest inValue = new SegipFrontend.ServicioSegip.BuscarPersonaCIRequest();
            inValue.Body = new SegipFrontend.ServicioSegip.BuscarPersonaCIRequestBody();
            inValue.Body.NumeroDocumento = NumeroDocumento;
            return ((SegipFrontend.ServicioSegip.SegipSoap)(this)).BuscarPersonaCIAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SegipFrontend.ServicioSegip.BuscarPersonasResponse SegipFrontend.ServicioSegip.SegipSoap.BuscarPersonas(SegipFrontend.ServicioSegip.BuscarPersonasRequest request) {
            return base.Channel.BuscarPersonas(request);
        }
        
        public SegipFrontend.ServicioSegip.Persona[] BuscarPersonas(string PrimerApellido, string SegundoApellido, string Nombres) {
            SegipFrontend.ServicioSegip.BuscarPersonasRequest inValue = new SegipFrontend.ServicioSegip.BuscarPersonasRequest();
            inValue.Body = new SegipFrontend.ServicioSegip.BuscarPersonasRequestBody();
            inValue.Body.PrimerApellido = PrimerApellido;
            inValue.Body.SegundoApellido = SegundoApellido;
            inValue.Body.Nombres = Nombres;
            SegipFrontend.ServicioSegip.BuscarPersonasResponse retVal = ((SegipFrontend.ServicioSegip.SegipSoap)(this)).BuscarPersonas(inValue);
            return retVal.Body.BuscarPersonasResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SegipFrontend.ServicioSegip.BuscarPersonasResponse> SegipFrontend.ServicioSegip.SegipSoap.BuscarPersonasAsync(SegipFrontend.ServicioSegip.BuscarPersonasRequest request) {
            return base.Channel.BuscarPersonasAsync(request);
        }
        
        public System.Threading.Tasks.Task<SegipFrontend.ServicioSegip.BuscarPersonasResponse> BuscarPersonasAsync(string PrimerApellido, string SegundoApellido, string Nombres) {
            SegipFrontend.ServicioSegip.BuscarPersonasRequest inValue = new SegipFrontend.ServicioSegip.BuscarPersonasRequest();
            inValue.Body = new SegipFrontend.ServicioSegip.BuscarPersonasRequestBody();
            inValue.Body.PrimerApellido = PrimerApellido;
            inValue.Body.SegundoApellido = SegundoApellido;
            inValue.Body.Nombres = Nombres;
            return ((SegipFrontend.ServicioSegip.SegipSoap)(this)).BuscarPersonasAsync(inValue);
        }
    }
}
