//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CotizacionInterfaz.ServicioCotizaciones {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioCotizaciones.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento fecha del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/obtenerCotizacion", ReplyAction="*")]
        CotizacionInterfaz.ServicioCotizaciones.obtenerCotizacionResponse obtenerCotizacion(CotizacionInterfaz.ServicioCotizaciones.obtenerCotizacionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/obtenerCotizacion", ReplyAction="*")]
        System.Threading.Tasks.Task<CotizacionInterfaz.ServicioCotizaciones.obtenerCotizacionResponse> obtenerCotizacionAsync(CotizacionInterfaz.ServicioCotizaciones.obtenerCotizacionRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento fecha del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/registrarCotizacion", ReplyAction="*")]
        CotizacionInterfaz.ServicioCotizaciones.registrarCotizacionResponse registrarCotizacion(CotizacionInterfaz.ServicioCotizaciones.registrarCotizacionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/registrarCotizacion", ReplyAction="*")]
        System.Threading.Tasks.Task<CotizacionInterfaz.ServicioCotizaciones.registrarCotizacionResponse> registrarCotizacionAsync(CotizacionInterfaz.ServicioCotizaciones.registrarCotizacionRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class obtenerCotizacionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="obtenerCotizacion", Namespace="http://tempuri.org/", Order=0)]
        public CotizacionInterfaz.ServicioCotizaciones.obtenerCotizacionRequestBody Body;
        
        public obtenerCotizacionRequest() {
        }
        
        public obtenerCotizacionRequest(CotizacionInterfaz.ServicioCotizaciones.obtenerCotizacionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class obtenerCotizacionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string fecha;
        
        public obtenerCotizacionRequestBody() {
        }
        
        public obtenerCotizacionRequestBody(string fecha) {
            this.fecha = fecha;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class obtenerCotizacionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="obtenerCotizacionResponse", Namespace="http://tempuri.org/", Order=0)]
        public CotizacionInterfaz.ServicioCotizaciones.obtenerCotizacionResponseBody Body;
        
        public obtenerCotizacionResponse() {
        }
        
        public obtenerCotizacionResponse(CotizacionInterfaz.ServicioCotizaciones.obtenerCotizacionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class obtenerCotizacionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public decimal obtenerCotizacionResult;
        
        public obtenerCotizacionResponseBody() {
        }
        
        public obtenerCotizacionResponseBody(decimal obtenerCotizacionResult) {
            this.obtenerCotizacionResult = obtenerCotizacionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class registrarCotizacionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="registrarCotizacion", Namespace="http://tempuri.org/", Order=0)]
        public CotizacionInterfaz.ServicioCotizaciones.registrarCotizacionRequestBody Body;
        
        public registrarCotizacionRequest() {
        }
        
        public registrarCotizacionRequest(CotizacionInterfaz.ServicioCotizaciones.registrarCotizacionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class registrarCotizacionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string fecha;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public decimal monto;
        
        public registrarCotizacionRequestBody() {
        }
        
        public registrarCotizacionRequestBody(string fecha, decimal monto) {
            this.fecha = fecha;
            this.monto = monto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class registrarCotizacionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="registrarCotizacionResponse", Namespace="http://tempuri.org/", Order=0)]
        public CotizacionInterfaz.ServicioCotizaciones.registrarCotizacionResponseBody Body;
        
        public registrarCotizacionResponse() {
        }
        
        public registrarCotizacionResponse(CotizacionInterfaz.ServicioCotizaciones.registrarCotizacionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class registrarCotizacionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string registrarCotizacionResult;
        
        public registrarCotizacionResponseBody() {
        }
        
        public registrarCotizacionResponseBody(string registrarCotizacionResult) {
            this.registrarCotizacionResult = registrarCotizacionResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : CotizacionInterfaz.ServicioCotizaciones.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<CotizacionInterfaz.ServicioCotizaciones.WebService1Soap>, CotizacionInterfaz.ServicioCotizaciones.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CotizacionInterfaz.ServicioCotizaciones.obtenerCotizacionResponse CotizacionInterfaz.ServicioCotizaciones.WebService1Soap.obtenerCotizacion(CotizacionInterfaz.ServicioCotizaciones.obtenerCotizacionRequest request) {
            return base.Channel.obtenerCotizacion(request);
        }
        
        public decimal obtenerCotizacion(string fecha) {
            CotizacionInterfaz.ServicioCotizaciones.obtenerCotizacionRequest inValue = new CotizacionInterfaz.ServicioCotizaciones.obtenerCotizacionRequest();
            inValue.Body = new CotizacionInterfaz.ServicioCotizaciones.obtenerCotizacionRequestBody();
            inValue.Body.fecha = fecha;
            CotizacionInterfaz.ServicioCotizaciones.obtenerCotizacionResponse retVal = ((CotizacionInterfaz.ServicioCotizaciones.WebService1Soap)(this)).obtenerCotizacion(inValue);
            return retVal.Body.obtenerCotizacionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CotizacionInterfaz.ServicioCotizaciones.obtenerCotizacionResponse> CotizacionInterfaz.ServicioCotizaciones.WebService1Soap.obtenerCotizacionAsync(CotizacionInterfaz.ServicioCotizaciones.obtenerCotizacionRequest request) {
            return base.Channel.obtenerCotizacionAsync(request);
        }
        
        public System.Threading.Tasks.Task<CotizacionInterfaz.ServicioCotizaciones.obtenerCotizacionResponse> obtenerCotizacionAsync(string fecha) {
            CotizacionInterfaz.ServicioCotizaciones.obtenerCotizacionRequest inValue = new CotizacionInterfaz.ServicioCotizaciones.obtenerCotizacionRequest();
            inValue.Body = new CotizacionInterfaz.ServicioCotizaciones.obtenerCotizacionRequestBody();
            inValue.Body.fecha = fecha;
            return ((CotizacionInterfaz.ServicioCotizaciones.WebService1Soap)(this)).obtenerCotizacionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CotizacionInterfaz.ServicioCotizaciones.registrarCotizacionResponse CotizacionInterfaz.ServicioCotizaciones.WebService1Soap.registrarCotizacion(CotizacionInterfaz.ServicioCotizaciones.registrarCotizacionRequest request) {
            return base.Channel.registrarCotizacion(request);
        }
        
        public string registrarCotizacion(string fecha, decimal monto) {
            CotizacionInterfaz.ServicioCotizaciones.registrarCotizacionRequest inValue = new CotizacionInterfaz.ServicioCotizaciones.registrarCotizacionRequest();
            inValue.Body = new CotizacionInterfaz.ServicioCotizaciones.registrarCotizacionRequestBody();
            inValue.Body.fecha = fecha;
            inValue.Body.monto = monto;
            CotizacionInterfaz.ServicioCotizaciones.registrarCotizacionResponse retVal = ((CotizacionInterfaz.ServicioCotizaciones.WebService1Soap)(this)).registrarCotizacion(inValue);
            return retVal.Body.registrarCotizacionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CotizacionInterfaz.ServicioCotizaciones.registrarCotizacionResponse> CotizacionInterfaz.ServicioCotizaciones.WebService1Soap.registrarCotizacionAsync(CotizacionInterfaz.ServicioCotizaciones.registrarCotizacionRequest request) {
            return base.Channel.registrarCotizacionAsync(request);
        }
        
        public System.Threading.Tasks.Task<CotizacionInterfaz.ServicioCotizaciones.registrarCotizacionResponse> registrarCotizacionAsync(string fecha, decimal monto) {
            CotizacionInterfaz.ServicioCotizaciones.registrarCotizacionRequest inValue = new CotizacionInterfaz.ServicioCotizaciones.registrarCotizacionRequest();
            inValue.Body = new CotizacionInterfaz.ServicioCotizaciones.registrarCotizacionRequestBody();
            inValue.Body.fecha = fecha;
            inValue.Body.monto = monto;
            return ((CotizacionInterfaz.ServicioCotizaciones.WebService1Soap)(this)).registrarCotizacionAsync(inValue);
        }
    }
}
