//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientePago.PagosServiceRef {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Deuda", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Deuda : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmpresaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ConceptoField;
        
        private double MontoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Empresa {
            get {
                return this.EmpresaField;
            }
            set {
                if ((object.ReferenceEquals(this.EmpresaField, value) != true)) {
                    this.EmpresaField = value;
                    this.RaisePropertyChanged("Empresa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Concepto {
            get {
                return this.ConceptoField;
            }
            set {
                if ((object.ReferenceEquals(this.ConceptoField, value) != true)) {
                    this.ConceptoField = value;
                    this.RaisePropertyChanged("Concepto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public double Monto {
            get {
                return this.MontoField;
            }
            set {
                if ((this.MontoField.Equals(value) != true)) {
                    this.MontoField = value;
                    this.RaisePropertyChanged("Monto");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PagosServiceRef.PagosServiceSoap")]
    public interface PagosServiceSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento CI del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/verDeuda", ReplyAction="*")]
        ClientePago.PagosServiceRef.verDeudaResponse verDeuda(ClientePago.PagosServiceRef.verDeudaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/verDeuda", ReplyAction="*")]
        System.Threading.Tasks.Task<ClientePago.PagosServiceRef.verDeudaResponse> verDeudaAsync(ClientePago.PagosServiceRef.verDeudaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento c del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PagarDeuda", ReplyAction="*")]
        ClientePago.PagosServiceRef.PagarDeudaResponse PagarDeuda(ClientePago.PagosServiceRef.PagarDeudaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PagarDeuda", ReplyAction="*")]
        System.Threading.Tasks.Task<ClientePago.PagosServiceRef.PagarDeudaResponse> PagarDeudaAsync(ClientePago.PagosServiceRef.PagarDeudaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class verDeudaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="verDeuda", Namespace="http://tempuri.org/", Order=0)]
        public ClientePago.PagosServiceRef.verDeudaRequestBody Body;
        
        public verDeudaRequest() {
        }
        
        public verDeudaRequest(ClientePago.PagosServiceRef.verDeudaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class verDeudaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CI;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string primerApellido;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string segundoApellido;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string nombres;
        
        public verDeudaRequestBody() {
        }
        
        public verDeudaRequestBody(string CI, string primerApellido, string segundoApellido, string nombres) {
            this.CI = CI;
            this.primerApellido = primerApellido;
            this.segundoApellido = segundoApellido;
            this.nombres = nombres;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class verDeudaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="verDeudaResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClientePago.PagosServiceRef.verDeudaResponseBody Body;
        
        public verDeudaResponse() {
        }
        
        public verDeudaResponse(ClientePago.PagosServiceRef.verDeudaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class verDeudaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ClientePago.PagosServiceRef.Deuda[] verDeudaResult;
        
        public verDeudaResponseBody() {
        }
        
        public verDeudaResponseBody(ClientePago.PagosServiceRef.Deuda[] verDeudaResult) {
            this.verDeudaResult = verDeudaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PagarDeudaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PagarDeuda", Namespace="http://tempuri.org/", Order=0)]
        public ClientePago.PagosServiceRef.PagarDeudaRequestBody Body;
        
        public PagarDeudaRequest() {
        }
        
        public PagarDeudaRequest(ClientePago.PagosServiceRef.PagarDeudaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PagarDeudaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ClientePago.PagosServiceRef.Deuda c;
        
        public PagarDeudaRequestBody() {
        }
        
        public PagarDeudaRequestBody(ClientePago.PagosServiceRef.Deuda c) {
            this.c = c;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PagarDeudaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PagarDeudaResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClientePago.PagosServiceRef.PagarDeudaResponseBody Body;
        
        public PagarDeudaResponse() {
        }
        
        public PagarDeudaResponse(ClientePago.PagosServiceRef.PagarDeudaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class PagarDeudaResponseBody {
        
        public PagarDeudaResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PagosServiceSoapChannel : ClientePago.PagosServiceRef.PagosServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PagosServiceSoapClient : System.ServiceModel.ClientBase<ClientePago.PagosServiceRef.PagosServiceSoap>, ClientePago.PagosServiceRef.PagosServiceSoap {
        
        public PagosServiceSoapClient() {
        }
        
        public PagosServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PagosServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PagosServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PagosServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientePago.PagosServiceRef.verDeudaResponse ClientePago.PagosServiceRef.PagosServiceSoap.verDeuda(ClientePago.PagosServiceRef.verDeudaRequest request) {
            return base.Channel.verDeuda(request);
        }
        
        public ClientePago.PagosServiceRef.Deuda[] verDeuda(string CI, string primerApellido, string segundoApellido, string nombres) {
            ClientePago.PagosServiceRef.verDeudaRequest inValue = new ClientePago.PagosServiceRef.verDeudaRequest();
            inValue.Body = new ClientePago.PagosServiceRef.verDeudaRequestBody();
            inValue.Body.CI = CI;
            inValue.Body.primerApellido = primerApellido;
            inValue.Body.segundoApellido = segundoApellido;
            inValue.Body.nombres = nombres;
            ClientePago.PagosServiceRef.verDeudaResponse retVal = ((ClientePago.PagosServiceRef.PagosServiceSoap)(this)).verDeuda(inValue);
            return retVal.Body.verDeudaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientePago.PagosServiceRef.verDeudaResponse> ClientePago.PagosServiceRef.PagosServiceSoap.verDeudaAsync(ClientePago.PagosServiceRef.verDeudaRequest request) {
            return base.Channel.verDeudaAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientePago.PagosServiceRef.verDeudaResponse> verDeudaAsync(string CI, string primerApellido, string segundoApellido, string nombres) {
            ClientePago.PagosServiceRef.verDeudaRequest inValue = new ClientePago.PagosServiceRef.verDeudaRequest();
            inValue.Body = new ClientePago.PagosServiceRef.verDeudaRequestBody();
            inValue.Body.CI = CI;
            inValue.Body.primerApellido = primerApellido;
            inValue.Body.segundoApellido = segundoApellido;
            inValue.Body.nombres = nombres;
            return ((ClientePago.PagosServiceRef.PagosServiceSoap)(this)).verDeudaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientePago.PagosServiceRef.PagarDeudaResponse ClientePago.PagosServiceRef.PagosServiceSoap.PagarDeuda(ClientePago.PagosServiceRef.PagarDeudaRequest request) {
            return base.Channel.PagarDeuda(request);
        }
        
        public void PagarDeuda(ClientePago.PagosServiceRef.Deuda c) {
            ClientePago.PagosServiceRef.PagarDeudaRequest inValue = new ClientePago.PagosServiceRef.PagarDeudaRequest();
            inValue.Body = new ClientePago.PagosServiceRef.PagarDeudaRequestBody();
            inValue.Body.c = c;
            ClientePago.PagosServiceRef.PagarDeudaResponse retVal = ((ClientePago.PagosServiceRef.PagosServiceSoap)(this)).PagarDeuda(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientePago.PagosServiceRef.PagarDeudaResponse> ClientePago.PagosServiceRef.PagosServiceSoap.PagarDeudaAsync(ClientePago.PagosServiceRef.PagarDeudaRequest request) {
            return base.Channel.PagarDeudaAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientePago.PagosServiceRef.PagarDeudaResponse> PagarDeudaAsync(ClientePago.PagosServiceRef.Deuda c) {
            ClientePago.PagosServiceRef.PagarDeudaRequest inValue = new ClientePago.PagosServiceRef.PagarDeudaRequest();
            inValue.Body = new ClientePago.PagosServiceRef.PagarDeudaRequestBody();
            inValue.Body.c = c;
            return ((ClientePago.PagosServiceRef.PagosServiceSoap)(this)).PagarDeudaAsync(inValue);
        }
    }
}
